// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx5rjmJT2tHSsjS0vBPCEHScmDaEXuckE',
    appId: '1:1872913033:web:cd7e064d89c3be77c71c58',
    messagingSenderId: '1872913033',
    projectId: 'interviewlink-e3afb',
    authDomain: 'interviewlink-e3afb.firebaseapp.com',
    storageBucket: 'interviewlink-e3afb.appspot.com',
    measurementId: 'G-MF1PT4JT56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19j1NzZVzh5kFc6xEjPRw8t_0zomEJXA',
    appId: '1:1872913033:android:200dfc9dec843fd0c71c58',
    messagingSenderId: '1872913033',
    projectId: 'interviewlink-e3afb',
    storageBucket: 'interviewlink-e3afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBvrGYtYRO6kRGssXXeEmWd0NhGrXgFW8',
    appId: '1:1872913033:ios:7812fca90c6e971fc71c58',
    messagingSenderId: '1872913033',
    projectId: 'interviewlink-e3afb',
    storageBucket: 'interviewlink-e3afb.appspot.com',
    androidClientId: '1872913033-s3v0l893rocvo3jrj5innitkj5a4k704.apps.googleusercontent.com',
    iosClientId: '1872913033-i6ll0eb30mqc26hosnafjbbqc76u38oc.apps.googleusercontent.com',
    iosBundleId: 'com.interviewlink.app.interviewLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBvrGYtYRO6kRGssXXeEmWd0NhGrXgFW8',
    appId: '1:1872913033:ios:7812fca90c6e971fc71c58',
    messagingSenderId: '1872913033',
    projectId: 'interviewlink-e3afb',
    storageBucket: 'interviewlink-e3afb.appspot.com',
    androidClientId: '1872913033-s3v0l893rocvo3jrj5innitkj5a4k704.apps.googleusercontent.com',
    iosClientId: '1872913033-i6ll0eb30mqc26hosnafjbbqc76u38oc.apps.googleusercontent.com',
    iosBundleId: 'com.interviewlink.app.interviewLink',
  );
}
